SELECT CONCAT(Name,"(",LEFT(Occupation,1),")")
FROM OCCUPATIONS

SELECT CONCAT("There are a total of ", COUNT(OCCUPATION)," ", OCCUPATION,"s.")
FROM OCCUPATIONS
GROUP BY OCCUPATION
ORDER BY COUNT(OCCUPATION),OCCUPATION